version: '3'

services:
  mongodb:
    build:
      context: .
      dockerfile: ./mongodb/Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - AirportAI

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mongodb://mongodb:27017/AirportAI
      AUTH_SECRET_KEY: A1B2C3D4E5F6G7H8I9J0K
    networks:
      - AirportAI
    depends_on:
      - mongodb

networks:
    AirportAI:
        name: mongodb

volumes:
  mongo-data:
