version: '3'

services:
  mongodb:
    build:
      context: .
      dockerfile: MongoDockerfile
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mongodb://root:password@mongodb:27017/AirportAI
    depends_on:
      - mongodb

volumes:
  mongo-data:
