FROM mongo:7.0

# Optionally copy a custom configuration file or scripts
# COPY ./initdb/ /docker-entrypoint-initdb.d/

# Expose the default MongoDB port
EXPOSE 27017

# The CMD directive is inherited from the official MongoDB image, which starts `mongod`